# Generated by Django 2.2.2 on 2019-06-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190612_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='automoviles'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='anio',
            field=models.IntegerField(verbose_name='año'),
        ),
    ]
